{
 "title": "GitCDN Cache Performance",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "description": "Percentage of requests that are served from either the pack cache or repo cache without pulling additional data from the upstream",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(git_cdn_cache_hit_bytes_sent_sum[$__range])) + sum(increase(git_cdn_cache_miss_bytes_sent_sum[$__range])) - (sum(increase(git_cdn_repo_cache_received_bytes_sum[$__range])) OR on() vector(0))) / sum(increase(git_cdn_total_bytes_sent_sum[$__range]))",
     "legendFormat": "Cache hit ratio"
    }
   ]
  },
  {
   "title": "Total Traffic Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(git_cdn_total_bytes_sent_sum[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Fetched from upstream",
   "type": "stat",
   "description": "Total data fetched from the upstream to populate the local repo cache.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(git_cdn_repo_cache_received_bytes_sum[$__range])) OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache Performance",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(git_cdn_cache_hit_bytes_sent_sum[$__range]))",
     "legendFormat": "Hit (pack cache)"
    },
    {
     "expr": "sum(increase(git_cdn_cache_miss_bytes_sent_sum[$__range])) - (sum(increase(git_cdn_repo_cache_received_bytes_sum[$__range])) OR on() vector(0))",
     "legendFormat": "Hit (repo cache)"
    },
    {
     "expr": "sum(increase(git_cdn_nocache_bytes_sent_sum[$__range]))",
     "legendFormat": "Not Cacheable"
    },
    {
     "expr": "sum(increase(git_cdn_repo_cache_received_bytes_sum[$__range])) OR on() vector(0)",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Data served (total over current time range)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(git_cdn_total_bytes_sent_sum[$__range])) by (instance)"
    }
   ]
  },
  {
   "title": "Requests Served (total over current time range)",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(git_cdn_response_status_total[$__range])) by (status))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cached Traffic Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(git_cdn_cache_hit_bytes_sent_sum[$__range])) + sum(increase(git_cdn_cache_miss_bytes_sent_sum[$__range])) - (sum(increase(git_cdn_repo_cache_received_bytes_sum[$__range])) OR on() vector(0))",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Un-cacheable Responses",
   "type": "stat",
   "description": "Total data sent responding to un-cacheable requests. The gitCDN cache is immediately consistent, and does not attempt to cache any requests that are not POST /git-upload-pack requests.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(git_cdn_nocache_bytes_sent_sum[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Git Traffic Served by cache instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(git_cdn_total_bytes_sent_sum[1m])) by (instance)",
     "legendFormat": "{{ kubecluster }}"
    }
   ]
  },
  {
   "title": "Cache Filesystem Used Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(1 - avg(min(git_cdn_workdir_filesystem_avail_bytes) without (pid) / max(git_cdn_workdir_filesystem_size_bytes) without (pid)) by (instance, gitcdn_hostname))",
     "legendFormat": "{{ instance }}/{{ gitcdn_hostname }}"
    }
   ]
  },
  {
   "title": "Pack Cache Hit/Miss Bandwidth",
   "type": "timeseries",
   "description": "The pack cache contains fully-cached git-upload-pack responses. Pack cache misses are served from the repo cache, then added to the pack cache. Responses which can not be cached (like GET info/refs) are shown here as N/A.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(git_cdn_pack_sent_bytes_total{cache_status=\"hit\"}[1m]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(rate(git_cdn_pack_sent_bytes_total{cache_status=\"miss\"}[1m]))",
     "legendFormat": "Miss"
    },
    {
     "expr": "sum(rate(git_cdn_nocache_bytes_sent_count[1m]))",
     "legendFormat": "N/A"
    }
   ]
  },
  {
   "title": "Upstream request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(git_cdn_upstream_responses_total[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Response status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(git_cdn_response_status_total[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(git_cdn_request_time_seconds_sum[10m]) / rate(git_cdn_request_time_seconds_count[10m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Filesystem Disk Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(1 - avg(aggregated_git_cdn_workdir_filesystem_avail_bytes / aggregated_git_cdn_workdir_filesystem_size_bytes) by (instance, gitcdn_hostname))",
     "legendFormat": "{{ instance }}/{{ gitcdn_hostname }}"
    }
   ]
  },
  {
   "title": "Pack cache evicted objects",
   "type": "timeseries",
   "description": "Number of objects evicted from the pack cache. Objects are (theoretically) evicted in a least-recently-used manner.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(git_cdn_pack_cache_evicted_bytes_count[1m]))",
     "legendFormat": "Evictions"
    }
   ]
  },
  {
   "title": "Pack cache evicted space",
   "type": "timeseries",
   "description": "Amount of data evicted from the pack cache as a result of the cache filling up. Least recently used data is evicted first.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(git_cdn_pack_cache_evicted_bytes_sum[1m]))",
     "legendFormat": "Evictions"
    }
   ]
  }
 ]
}